name: Sync Mattejakten

on:
  push:
    branches: [main]
    paths:
      - 'matematik/**'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: Bombaklubb
          repositories: mattejakten,M

      - name: Push to mattejakten
        env:
          TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"
          git config --global url."https://x-access-token:${TOKEN}@github.com/".insteadOf "https://github.com/"
          git remote add target https://github.com/Bombaklubb/mattejakten.git
          git subtree push --prefix=matematik target main
