name: Sync Läsjakten

on:
  push:
    branches: [main]
    paths:
      - 'lasforstaelse/**'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to lasjakten
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"
          git remote add target https://x-access-token:${{ secrets.SYNC_TOKEN }}@github.com/Bombaklubb/lasjakten.git
          git subtree push --prefix=lasforstaelse target main
